if: type != push OR branch = main

language: rust
matrix:
  include:
    - rust: stable
      name: check if `cargo fmt --all` is applied
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check

    - rust: stable
      name: clippy
      before_script: rustup component add clippy
      script: cargo clippy --all -- -D warnings

    - rust: 1.46.0
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  - cargo test

jobs:
  allow_failures:
    - name: clippy
