[package]
name = "scorpion"
version = "0.1.0"
authors = ["Brett Wilcox <brett@scorpion.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
